language: go

go:
  - "1.12"

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      name: gotest
      script: go test .
    - stage: build
      name: gobuild
      script: go build .
